export const POST_TYPES = {
  LOAD_POSTS: "LOAD_POSTS",
  GET_ALL_POSTS: "GET_ALL_POSTS",
  DELETE_POST: "DELETE_POST",
  LIKE_POST: "LIKE_POST",
  COMMENT_POST: "COMMENT_POST",
  ADD_POST: "ADD_POST",
};

export const USER_TYPES = {
  LOAD_LOGIN: "LOAD_LOGIN",
  LOAD_SIGNUP: "LOAD_SIGNUP",
  SIGN_IN_USER: "SIGN_IN_USER",
  SIGN_UP_USER: "SIGN_UP_USER",
  IS_LOGGED_IN: "IS_LOGGED_IN",
};
